apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: custom-nginx-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/josefloressv/argocd
    targetRevision: HEAD
    path: nginx/
   
  destination:
    server: https://kubernetes.default.svc
    namespace: custom-nginx

  syncPolicy:
    syncOptions:
      - CreateNamespace=true  
    automated:
      prune: true
      selfHeal: true