apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html-configmap
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Nginx</title>
        <style>
            body {
                background-color: #1c262d;
                color: #eee;
                font-family: sans-serif;
            }
        </style>
    </head>
    <body>
        <div style="text-align: center;">
            <img src="https://nginx.org/img/nginx_logo_dark.png" alt="Nginx Logo">
            <h1>Hello, from Nginx!</h1>
        </div>
        
    </body>
    </html>